### ISSUE TITLE
input must be aligned or not

### ISSUE THREAD

**Issue by janicevidal** [BeierZhu/Sturcture-Coherency-Face-Alignment#5]
Face images in the given train set was all aligned, is it necessary to do so？and how to process the input when inference?

**Comment by BeierZhu** [comment]
1) the reason to align the input image is that we use large transform, e.g, large random rotation, translation and scale. Align the input to a neutral position helps the we set a uniform transform for all images. 2) during the inference, it’s not necessary to align the image, since we already use large transform to cover diverse head pose distribution. BTW, in industry, the face alignment product usually first uses a lightweight landmark detector to align a face image then use a high precision model to detect landmarks.

**Comment by janicevidal** [comment]
Thanks!!
